import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

// CLAUDE.md rule 7's banned-everywhere list. The two structural bans in that
// rule — "it's not just X, it's Y" and "any sentence whose only content is
// that the subject is interesting" — aren't literal phrases and aren't
// checked here; they need a reader, not a regex. Extend this list as rule 7
// grows.
export const BANNED_PHRASES = [
  "delve",
  "tapestry",
  "landscape",
  "journey",
  "realm",
  "dive into",
  "unlock",
  "in today's",
  "explore the fascinating",
];

function findHtmlFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...findHtmlFiles(full));
    } else if (entry.endsWith(".html")) {
      results.push(full);
    }
  }
  return results;
}

const ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  "#39": "'",
  apos: "'",
  nbsp: " ",
  lsquo: "'",
  rsquo: "'",
};

function decodeEntities(text: string): string {
  return text.replace(
    /&(#39|amp|lt|gt|quot|apos|nbsp|lsquo|rsquo);/g,
    (_, name) => ENTITIES[name],
  );
}

// The build's markdown renderer turns straight apostrophes into typographic
// ones (U+2018/U+2019) before this test ever sees the HTML — "today's" is
// rendered "today’s". Normalise curly quotes to straight ones so a banned
// phrase written with a plain apostrophe still matches what the build
// actually emits, without needing a second, curly-quoted copy of every entry.
function normaliseQuotes(text: string): string {
  return text.replace(/[‘’]/g, "'");
}

// Rendered body text, with <script>/<style>, anything inside <code> or
// <pre>, and any element carrying a `data-specimen` attribute removed first.
// `data-specimen` is the proposed contract for a quoted mistranslation
// (e.g. `<blockquote data-specimen>`): a real specimen may legitimately
// contain a banned word, and disclosing that belongs on the page for the
// reader, not in a workaround that shrinks this list. Quote normalisation
// happens later, in findBannedPhrases, so this step is reusable for fixture
// strings that are already plain text.
function extractText(html: string): string {
  const withoutOpaque = html
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<pre\b[^>]*>[\s\S]*?<\/pre>/gi, " ")
    .replace(/<code\b[^>]*>[\s\S]*?<\/code>/gi, " ")
    .replace(/<(\w+)\b[^>]*\bdata-specimen\b[^>]*>[\s\S]*?<\/\1>/gi, " ");
  return decodeEntities(withoutOpaque.replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ");
}

function escapeRegExp(word: string): string {
  return word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Standard-English inflections of a base word, generated by spelling rule
// rather than an open "\w*" suffix — a wildcard also matches unrelated words
// that merely start the same way ("dive" -> \bdiv\w*\b also caught
// "divided" and "division"). Consonant+y swaps to "-ies"/"-ied" ("tapestry"
// -> "tapestries"); a trailing silent e is dropped before "-ed"/"-ing"
// ("dive" -> "diving", not "diveing"); anything else takes plain
// "-s"/"-es"/"-ed"/"-ing", doubling a final single consonant after a single
// vowel where English doubles it. Some generated forms aren't real words
// (e.g. "realmed") — harmless, since a non-word never appears in real text
// to false-match against.
function regularInflections(word: string): string[] {
  const forms = new Set<string>([word]);
  if (/[^aeiou]y$/i.test(word)) {
    const stem = word.slice(0, -1);
    forms.add(`${stem}ies`);
    forms.add(`${stem}ied`);
    forms.add(`${word}ing`);
  } else if (/e$/i.test(word) && !/ee$/i.test(word)) {
    const stem = word.slice(0, -1);
    forms.add(`${word}s`);
    forms.add(`${stem}ed`);
    forms.add(`${stem}ing`);
  } else {
    const sibilant = /(s|sh|ch|x|z)$/i.test(word);
    const doubles = /[^aeiou][aeiou][^aeiouwxy]$/i.test(word);
    const stem = doubles ? word + word.slice(-1) : word;
    forms.add(sibilant ? `${word}es` : `${word}s`);
    forms.add(`${stem}ed`);
    forms.add(`${stem}ing`);
  }
  return [...forms];
}

// Only the phrase's head word inflects ("dive" in "dive into", "explore" in
// "explore the fascinating") — every entry in this list puts the verb/noun
// first. Short words (len <= 3, e.g. "in") are left exact: they're function
// words in this list, not the term that inflects.
function headPattern(word: string): string {
  if (word.length <= 3) return escapeRegExp(word);
  return `(?:${regularInflections(word).map(escapeRegExp).join("|")})`;
}

function phraseRegex(phrase: string): RegExp {
  const [head, ...rest] = phrase.split(/\s+/);
  const pattern = [headPattern(head), ...rest.map(escapeRegExp)].join("\\s+");
  return new RegExp(`\\b${pattern}\\b`, "i");
}

const PHRASE_MATCHERS = BANNED_PHRASES.map((phrase) => ({ phrase, regex: phraseRegex(phrase) }));

// The check on the check: runs the matcher against plain-text fixtures, not
// dist/, so a false positive introduced by a future BANNED_PHRASES entry (or
// a future change to the matching logic) shows up in "banned-phrase matcher"
// below instead of needing to be re-derived by hand against the real site.
export function findBannedPhrases(text: string): string[] {
  const normalised = normaliseQuotes(text).replace(/\s+/g, " ");
  return PHRASE_MATCHERS.filter(({ regex }) => regex.test(normalised)).map(({ phrase }) => phrase);
}

const htmlFiles = findHtmlFiles(resolve("dist"));

describe("voice", () => {
  it("builds at least one page to check", () => {
    expect(htmlFiles.length).toBeGreaterThan(0);
  });

  it.each(htmlFiles)("keeps %s free of banned phrases", (file) => {
    const hits = findBannedPhrases(extractText(readFileSync(file, "utf8")));
    expect(hits, `${file} uses banned phrase(s): ${hits.join(", ")}`).toEqual([]);
  });
});

describe("banned-phrase matcher", () => {
  const mustMatch: Array<[phrase: string, text: string]> = [
    ["delve", "delving into the record"],
    ["tapestry", "tapestries of meaning"],
    ["journey", "journeys and returns"],
    ["unlock", "unlocked the cabinet"],
    ["unlock", "the essay unlocks nothing new"],
    ["dive into", "diving into the corpus"],
    ["in today's", "in today’s classroom"],
  ];

  it.each(mustMatch)('catches "%s" in "%s"', (phrase, text) => {
    expect(findBannedPhrases(text)).toContain(phrase);
  });

  // Each of these shares a prefix or stem with a banned phrase but is
  // ordinary English a session or lecture page will actually use — an open
  // "\w*" suffix used to catch all three "dive into" cases below.
  const mustNotMatch = [
    "The semester is divided into three parts.",
    "Divide into pairs.",
    "a division into weeks",
    "the archive is unlockable to researchers",
    "journalism about the course",
  ];

  it.each(mustNotMatch)('does not flag "%s"', (text) => {
    expect(findBannedPhrases(text)).toEqual([]);
  });
});
